table FREQ_INCONSISTENCIAS
    annotation PBI_ResultType = Table

    partition FREQ_INCONSISTENCIAS-partition = m
        mode: import
        source =
            let
                    src = Excel.Workbook(File.Contents("C:/Users/Arthur/Documents/VS Code/Projetos/cadastral-actuarial-pipeline/results/reports/powerbi_data.xlsx"), null, true),
                    sheet = src{[Item="FREQ_INCONSISTENCIAS",Kind="Sheet"]}[Data],
                    promoted = Table.PromoteHeaders(sheet, [PromoteAllScalars=true]),
                    typed = Table.TransformColumnTypes(promoted, { {"OCORRENCIAS", Int64.Type}, {"PCT_TOTAL", type number} })
            in
                    typed

    column CODIGO
        dataType: string
    column SEVERIDADE
        dataType: string
    column CAMPO
        dataType: string
    column OCORRENCIAS
        dataType: int64
    column PCT_TOTAL
        dataType: double
